### ISSUE TITLE
Cập nhật hệ tọa độ VN2000

### ISSUE THREAD

**Issue by ethernal-serenade** [soiqualang/ArcGIS-VN2000#1]
ArcGIS 10.8.1 có tọa độ này luôn anh ạ
Anh đâu cần phải lưu riêng đâu nhỉ

**Comment by soiqualang** [comment]
À, clone ra để dành cho những người đang dùng bản ArcGIS ver thấp hơn đó em. Bữa bạn anh bị nên anh mới phải clone cái này và làm cái này https://dothanhlong.org/add-vn2000-projection-in-arcgis/ =))

**Comment by ethernal-serenade** [comment]
Oke anh êi
